### PR TITLE
Next web feature branch

### PR DESCRIPTION
**Pull request by mosesmuchemi**
creating a pull request for stickler and TSE review

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Hi @mosesmuchemi  and @silverside3000 :wave:  
### The clone looks great :wave:  
Before we give this a :+1: , let's fix a few issues:
**[REQUIRED]** 
* The TNW logo on the navigation bar should be visible only on medium and small screen sizes.

**[OPTIONAL]** 
* You can give the articles a dark background gradient to make the white text more visible.
* Place the text on the bottom part of the article to make it look more like the original page.
Screenshot from 2019-10-09 16-20-21

**After implementing the change, submit another request for review** 
Happy coding :computer:

**Comment by mosesmuchemi** [comment]
Made the TNW logo visible on small and medium-size screens as per TSE recommendation.

**Comment by mosesmuchemi** [comment]
fixed formatting lint errors

**Review by whiz25 — APPROVED** [review]
## Good job :clap: 
You have made the requested changes and it's, therefore, a :+1: from me. Go ahead and merge.
Use ```Martin Afani``` when filling the form. Happy coding.

**Comment by mosesmuchemi** [comment]
Thanks, Martin and Wathigo for the constructive reviews

**Comment by mosesmuchemi** [comment]
Merging the feature and master branches project after successful automated Stickler and manual TSE reviews.

**Pull request merged**
